apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "speechka.fullname" . }}
  labels:
		{{- include "speechka.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
			{{- include "speechka.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
				{{- include "speechka.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: speechka
          image: {{ .Values.image }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "speechka.fullname" . }}-configuration
              mountPath: /speechka/.config
              readOnly: true
          ports:
            - containerPort: 3000
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: "example-speechka-user"
            - name: POSTGRES_PASSWORD
              value: "example-speechka-pass"
            - name: POSTGRES_DB
              value: "speechka"
          ports:
            - containerPort: 5432
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
      volumes:
        - name: {{ include "speechka.fullname" . }}-configuration
          configMap:
            name: {{ include "speechka.fullname" . }}-configuration
